
version: 2

models:
    - name: my_first_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "model on city bike trip data "
            tests:
               
                - null

    - name: my_second_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "model on city bike trip data"
            tests:
                - null
    
    - name: my_third_dbt_model
      description: "A starter dbt model"
      columns:
          - name: id
            description: "model on city bike trip data"
            tests:
                - unique
                - not_null
